/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jezhumble_javasysmon_MacOsXMonitor */

#ifndef _Included_com_jezhumble_javasysmon_MacOsXMonitor
#define _Included_com_jezhumble_javasysmon_MacOsXMonitor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    numCpus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_numCpus
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    cpuFrequencyInHz
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_cpuFrequencyInHz
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    uptimeInSeconds
 * Signature: ()J
 */
 JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_uptimeInSeconds
   (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    numCpus
 * Signature: ()I
 */
 JNIEXPORT jint JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_currentPid
   (JNIEnv *, jobject);
		
/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    cpuTimes
 * Signature: ()Lcom/jezhumble/javasysmon/CpuTimes;
 */
 JNIEXPORT jobject JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_cpuTimes
   (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    physical
 * Signature: ()Lcom/jezhumble/javasysmon/MemoryStats;
 */
 JNIEXPORT jobject JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_physical
   (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    swap
 * Signature: ()Lcom/jezhumble/javasysmon/MemoryStats;
 */
 JNIEXPORT jobject JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_swap
   (JNIEnv *, jobject);
	
/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    processTable
 * Signature: ()[Lcom/jezhumble/javasysmon/ProcessInfo;
 */	
 JNIEXPORT jobjectArray JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_processTable
   (JNIEnv *, jobject);
	
/*
 * Class:     com_jezhumble_javasysmon_MacOsXMonitor
 * Method:    killProcess
 * Signature: (I)V
 */
 JNIEXPORT void JNICALL Java_com_jezhumble_javasysmon_MacOsXMonitor_killProcess
   (JNIEnv *, jobject, jint);
	
	
#ifdef __cplusplus
}
#endif
#endif
