/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jezhumble_javasysmon_WindowsMonitor */

#ifndef _Included_com_jezhumble_javasysmon_WindowsMonitor
#define _Included_com_jezhumble_javasysmon_WindowsMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    cpuUsage
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_cpuUsage
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    totalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_totalMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    freeMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_freeMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    totalSwap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_totalSwap
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    freeSwap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_freeSwap
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    numCpus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_numCpus
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_WindowsMonitor
 * Method:    cpuFrequency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_cpuFrequency
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
