  /* DO NOT EDIT THIS FILE - it is machine generated */
  #include <jni.h>
  /* Header for class com_jezhumble_javasysmon_SolarisMonitor */

  #ifndef _Included_com_jezhumble_javasysmon_WindowsMonitor
  #define _Included_com_jezhumble_javasysmon_WindowsMonitor
  #ifdef __cplusplus
  extern "C" {
  #endif

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    numCpus
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_numCpus
    (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    cpuFrequencyInHz
   * Signature: ()I
   */
  JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_cpuFrequencyInHz
    (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    uptimeInSeconds
   * Signature: ()J
   */
   JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_uptimeInSeconds
     (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    numCpus
   * Signature: ()I
   */
   JNIEXPORT jint JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_currentPid
     (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    cpuTimes
   * Signature: ()Lcom/jezhumble/javasysmon/CpuTimes;
   */
   JNIEXPORT jobject JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_cpuTimes
     (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    physical
   * Signature: ()Lcom/jezhumble/javasysmon/MemoryStats;
   */
   JNIEXPORT jobject JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_physical
     (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    swap
   * Signature: ()Lcom/jezhumble/javasysmon/MemoryStats;
   */
   JNIEXPORT jobject JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_swap
     (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    processTable
   * Signature: ()[Lcom/jezhumble/javasysmon/ProcessInfo;
   */	
   JNIEXPORT jobjectArray JNICALL Java_com_jezhumble_javasysmon_WindowsMonitor_processTable
     (JNIEnv *, jobject);

  /*
   * Class:     com_jezhumble_javasysmon_WindowsMonitor
   * Method:    killProcess
   * Signature: (I)V
   */
   JNIEXPORT void JNICALL Java_com_jezhumble_javasysmon_WindowMonitor_killProcess
     (JNIEnv *, jobject, jint);

  #ifdef __cplusplus
  }
  #endif
  #endif
