/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jezhumble_javasysmon_SolarisMonitor */

#ifndef _Included_com_jezhumble_javasysmon_SolarisMonitor
#define _Included_com_jezhumble_javasysmon_SolarisMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    cpuUsage
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_cpuUsage
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    totalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_totalMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    freeMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_freeMemory
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    totalSwap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_totalSwap
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    freeSwap
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_freeSwap
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    numCpus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_numCpus
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    cpuFrequency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_cpuFrequency
  (JNIEnv *, jobject);

/*
 * Class:     com_jezhumble_javasysmon_SolarisMonitor
 * Method:    uptimeInSeconds
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jezhumble_javasysmon_SolarisMonitor_uptimeInSeconds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
